In [1]:
from src.env import GridWorldRenderer, GridWorldEnv, GET_RANDOM_MAP
from src.agent import QLearningAgent, SarsaAgent
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from src.utils import qtable_heatmap, agent_decision

In [2]:
# map = [
#     ['A', 'R', '', 'S'],
#     ['', '', '', ''],
#     ['B', '', 'B', 'R'],
#     ['', '', '', 'G']
#     ]

# rows = 4 
# cols =4 

# def gen_obj():
#     choices = ['R', 'S', 'B', '-']
#     weights =  [0.05, 0.05, 0.05, 0.85]
#     return np.random.choice(choices, p = weights)

# map = [[gen_obj() for _ in range(rows)] for _ in range(cols)]
# map[0][0] = 'A'
# map[rows - 1][cols - 1] = 'G'

# map = [''.join(row) for row in map]

# for row in map:
#     print(row)

In [3]:
reward_dict = {
    'G': 3,
    'B': 1,
    'R': -1,
    'S': -1,
    'out_of_bound': -1,
    'visited_state': -1,
    'terminated': -1,
}
map = [
    "A--B",
    "----",
    "B---",
    "---G",
]
map = GET_RANDOM_MAP(20,20)
#print map
for row in map:
    print(row)
env = GridWorldEnv(map = map, reward_dict = reward_dict, max_timestep = 100)

A-----B-----------SB
-------------B------
-----------BS-B----S
-------R-----------S
--------B--B-----R--
----------------R---
----R-BR------------
-B---R------R-------
-------------S------
----R-------S--R---S
---B-------B--S-B---
--B--S----B--BR-B--B
--B---RR--S--------B
--BS---B----------SR
----RB-----R---S--S-
-R------------------
S--------------B----
--------S------S--R-
-----B-----------B--
S--------------R--RG


# Q learning

In [4]:
agent = QLearningAgent(env)
agent.train()
agent.save()
# agent.load('./qtable.npy')
print(agent.qtable)

ep = 58, eposilon = 0.97, reached goals = 0, terminated = 0:   0%|          | 40/10000 [00:00<00:25, 394.52it/s]

QLEARNING TRAINING


ep = 9999, eposilon = 0.01, reached goals = 2144, terminated = 0: 100%|██████████| 10000/10000 [00:29<00:00, 335.56it/s]


[[-1.49042317 -0.64209647 -0.64160872 -1.48376112]
 [-1.19153881 -0.55025933 -0.55801542 -0.64810077]
 [-0.98661124 -0.4397276  -0.44990751 -1.00249179]
 ...
 [-0.12022139 -0.11223812 -0.15307163 -0.11794228]
 [-0.00551715  1.04498445 -0.03887587 -0.05917652]
 [ 0.          0.          0.          0.        ]]


In [5]:
env.reset()
print(env)

ENV MAP
['A', '-', '-', '-', '-', '-', 'B', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'S', 'B']
['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'B', '-', '-', '-', '-', '-', '-']
['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'B', 'S', '-', 'B', '-', '-', '-', '-', 'S']
['-', '-', '-', '-', '-', '-', '-', 'R', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'S']
['-', '-', '-', '-', '-', '-', '-', '-', 'B', '-', '-', 'B', '-', '-', '-', '-', '-', 'R', '-', '-']
['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'R', '-', '-', '-']
['-', '-', '-', '-', 'R', '-', 'B', 'R', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-']
['-', 'B', '-', '-', '-', 'R', '-', '-', '-', '-', '-', '-', 'R', '-', '-', '-', '-', '-', '-', '-']
['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'S', '-', '-', '-', '-', '-', '-']
['-', '-', '-', '-', 'R', '-', '-', '-', '-', '-', '-', '-', 'S', '-', '-', 'R', '-

In [6]:
#Test the enviroment rewards and stuff
# info = env.step(2)
# print(env.state)
# for row in env.map:
#     print(row)
# print(info)

In [7]:
# env.render_simple(agent)

In [8]:
env.render(agent)

/Users/jamesnguyen/Desktop/ml_projects/rl/grid_world/src
exit
Terminated
