In [1]:
from src.env import GridWorldRenderer, GridWorldEnv, GET_RANDOM_MAP
from src.agent import QLearningAgent, SarsaAgent
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from src.utils import qtable_heatmap, agent_decision
import json

In [2]:
# map = [
#     ['A', 'R', '', 'S'],
#     ['', '', '', ''],
#     ['B', '', 'B', 'R'],
#     ['', '', '', 'G']
#     ]

# rows = 4 
# cols =4 

# def gen_obj():
#     choices = ['R', 'S', 'B', '-']
#     weights =  [0.05, 0.05, 0.05, 0.85]
#     return np.random.choice(choices, p = weights)

# map = [[gen_obj() for _ in range(rows)] for _ in range(cols)]
# map[0][0] = 'A'
# map[rows - 1][cols - 1] = 'G'

# map = [''.join(row) for row in map]

# for row in map:
#     print(row)

In [3]:
map = [
'A-B-BR---S---------S',
'S-SB----RB-S-R--B---',
'B----BB---------S-R-',
'---------RB--R----S-',
'RR------------S----S',
'-------B------------',
'-----R--S----------S',
'-----R-----R----B---',
'-S------S-------B---',
'------R------R-R----',
'-------B------------',
'----------B--------B',
'--S----B-----S------',
'-R--------------BB--',
'-------B-----------R',
'-------S----R-----RB',
'---R---------S--S---',
'--------------SB----',
'B-------------------',
'--S---B--BSS-B----RG',
]

In [2]:
reward_dict = {
    'G': 3,
    'B': 1,
    'R': -1,
    'S': -2,
    'out_of_bound': -1,
    'visited_state': -1,
    'terminated': -1,
}
# map = [
#     "A--B",
#     "----",
#     "B---",
#     "---G",
# ]
# map = GET_RANDOM_MAP(20,20)
#print map
for row in map:
    print(row)
env = GridWorldEnv(map = map, reward_dict = reward_dict, max_timestep = 100)

TypeError: 'type' object is not iterable

# Q learning

In [4]:
agent = QLearningAgent(env, n_training_eps = 50000, learning_rate = 0.01, decay_rate = 5e-5)
# agent.train()
# agent.save()
# agent.load('./qtable.npy')
id = '5c9a33fa'
agent.load(id)
print(agent.qtable)

NameError: name 'env' is not defined

In [5]:
id = agent.save_attempt()

AttributeError: 'QLearningAgent' object has no attribute 'save_attempt'

In [6]:
env.reset()
print(env)

ENV MAP
['A', '-', 'B', '-', 'B', 'R', '-', '-', '-', 'S', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'S']
['S', '-', 'S', 'B', '-', '-', '-', '-', 'R', 'B', '-', 'S', '-', 'R', '-', '-', 'B', '-', '-', '-']
['B', '-', '-', '-', '-', 'B', 'B', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'S', '-', 'R', '-']
['-', '-', '-', '-', '-', '-', '-', '-', '-', 'R', 'B', '-', '-', 'R', '-', '-', '-', '-', 'S', '-']
['R', 'R', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'S', '-', '-', '-', '-', 'S']
['-', '-', '-', '-', '-', '-', '-', 'B', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-']
['-', '-', '-', '-', '-', 'R', '-', '-', 'S', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'S']
['-', '-', '-', '-', '-', 'R', '-', '-', '-', '-', '-', 'R', '-', '-', '-', '-', 'B', '-', '-', '-']
['-', 'S', '-', '-', '-', '-', '-', '-', 'S', '-', '-', '-', '-', '-', '-', '-', 'B', '-', '-', '-']
['-', '-', '-', '-', '-', '-', 'R', '-', '-', '-', '-', '-', '-', 'R', '-', 'R', '-

In [7]:
#Test the enviroment rewards and stuff
# info = env.step(2)
# print(env.state)
# for row in env.map:
#     print(row)
# print(info)

In [8]:
# env.render_simple(agent)

In [9]:
# env.render(agent)

In [26]:
import uuid

In [37]:
def save_attempt(map, qtable, id = None):
    if id == None:
        id = str(uuid.uuid4()).split('-')[0]
    attemp_dir = f'./attempts/{id}'

    if os.path.exists(attemp_dir) == False:
        os.path.join(attemp_dir, f'attemp_{1}')
        os.makedirs(attemp_dir)
    map_path = os.path.join(attemp_dir,'map.json')
    with open(map_path, 'w') as mapfile:
        json.dump(map, mapfile)
    
    qtable_path = os.path.join(attemp_dir,'qtable.npy')
    with open(qtable_path, 'wb') as qtablefile:
        np.save(qtablefile, qtable)
    return id

def load_attempt(id):
    attemp_dir = f'./attempts/{id}'
    if os.path.exists(attemp_dir):

        map_path = os.path.join(attemp_dir,'map.json')
        with open(map_path, 'rb') as mapfile:
            map = json.load(mapfile)
        
        qtable_path = os.path.join(attemp_dir,'qtable.npy')
        with open(qtable_path, 'rb') as qtablefile:
            qtable = np.load(qtablefile)
        
        return map, qtable
    else:
        raise FileNotFoundError(f"{attemp_dir} directory not found")
    

In [38]:
id = save_attempt(map, agent.qtable) 

In [39]:
map, qtable = load_attempt(id)
print(map)
print(qtable)

['A-B-BR---S---------S', 'S-SB----RB-S-R--B---', 'B----BB---------S-R-', '---------RB--R----S-', 'RR------------S----S', '-------B------------', '-----R--S----------S', '-----R-----R----B---', '-S------S-------B---', '------R------R-R----', '-------B------------', '----------B--------B', '--S----B-----S------', '-R--------------BB--', '-------B-----------R', '-------S----R-----RB', '---R---------S--S---', '--------------SB----', 'B-------------------', '--S---B--BSS-B----RG']
[[-0.64014482  0.38787197 -1.80258691 -0.6411766 ]
 [-0.39285859  0.68549678 -0.56247196  0.01869859]
 [-0.92983793  0.0493947  -2.00952037 -0.39513618]
 ...
 [ 1.65248637  1.85        0.75748632  0.75098627]
 [ 2.04667638  3.          1.84997202  1.06636825]
 [ 0.          0.          0.          0.        ]]
