In [1]:
from src.env import GridWorldRenderer, GridWorldEnv
from src.agent import QLearningAgent, SarsaAgent
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from src.utils import qtable_heatmap, agent_decision

In [2]:
# map = [
#     ['A', 'R', '', 'S'],
#     ['', '', '', ''],
#     ['B', '', 'B', 'R'],
#     ['', '', '', 'G']
#     ]

# rows = 4 
# cols =4 

# def gen_obj():
#     choices = ['R', 'S', 'B', '-']
#     weights =  [0.05, 0.05, 0.05, 0.85]
#     return np.random.choice(choices, p = weights)

# map = [[gen_obj() for _ in range(rows)] for _ in range(cols)]
# map[0][0] = 'A'
# map[rows - 1][cols - 1] = 'G'

# map = [''.join(row) for row in map]

# for row in map:
#     print(row)

In [2]:
reward_dict = {
    'G': 3,
    'B': 1,
    'R': -1,
    'S': -1,
    'out_of_bound': -1,
    'visited_state': -1,
    'terminated': -1,
}
map = [
    "A--B",
    "----",
    "B---",
    "---G",
]
env = GridWorldEnv(map = map, reward_dict = reward_dict, max_timestep = 100)

In [36]:
sarsa = SarsaAgent(env)
sarsa.train()
sarsa.save('sarsa_qtable.npy')
print(sarsa.qtable)

ep = 148, eposilon = 0.93, reached goals = 134, terminated = 0:   1%|          | 75/10000 [00:00<00:13, 737.63it/s]

SARSA TRAINING


ep = 8179, eposilon = 0.02, reached goals = 8106, terminated = 0:  81%|████████  | 8124/10000 [00:09<00:01, 1386.19it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

ep = 9999, eposilon = 0.01, reached goals = 9925, terminated = 0: 100%|██████████| 10000/10000 [00:11<00:00, 889.57it/s]

[[-1.42014425 -0.46245278  0.14164702 -1.40493254]
 [-1.05856176 -0.23099248 -0.52402953 -0.59691081]
 [-0.79399291  0.74537391 -0.83694308 -1.20919718]
 [-1.72403169 -1.71541529 -0.87816614 -0.87920329]
 [-0.62789093 -0.41550981  0.90560567 -0.80798767]
 [-0.57965451 -0.50216754 -0.19600559 -0.52920245]
 [-0.5633655  -0.57262658 -0.56176709 -0.58996736]
 [-0.66059498 -0.89568292 -0.65680934 -0.72811388]
 [-0.73758914 -0.09995604  1.99532199 -0.16082498]
 [-0.69713244 -0.53534382  0.60003309  0.14670489]
 [-0.62467674 -0.55367622 -0.4199474  -0.3847657 ]
 [-0.66406763 -0.73156851 -0.59060782 -0.58946903]
 [ 0.          0.          0.          0.        ]
 [-0.58434254 -0.47074651 -0.27738046  1.95836396]
 [-0.61129755 -0.59957731 -0.69124899  0.31085257]
 [-0.64496672 -0.69733848 -0.6965625  -0.52765188]]


In [37]:
# qtable_heatmap(agent.qtable)
for row in map:
    print(row)
agent_decision(sarsa.qtable)

A--B
----
----
G---


[['down', 'right', 'right', 'down'],
 ['down', 'down', 'down', 'down'],
 ['down', 'down', 'left', 'left'],
 ['up', 'left', 'left', 'left']]