In [1]:
from src.env import GridWorldRenderer, GridWorldEnv
from src.agent import QLearningAgent, SarsaAgent
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from src.utils import qtable_heatmap, agent_decision

In [6]:
# map = [
#     ['A', 'R', '', 'S'],
#     ['', '', '', ''],
#     ['B', '', 'B', 'R'],
#     ['', '', '', 'G']
#     ]

# rows = 4 
# cols =4 

# def gen_obj():
#     choices = ['R', 'S', 'B', '-']
#     weights =  [0.05, 0.05, 0.05, 0.85]
#     return np.random.choice(choices, p = weights)

# map = [[gen_obj() for _ in range(rows)] for _ in range(cols)]
# map[0][0] = 'A'
# map[rows - 1][cols - 1] = 'G'

# map = [''.join(row) for row in map]

# for row in map:
#     print(row)

In [5]:
reward_dict = {
    'G': 10,
    'B': 10,
    'R': -1,
    'S': -1,
    'out_of_bound': -2,
    'visited_state': -3,
    'terminated': -1,
}
map = [
    "A--B",
    "--B-",
    "R---",
    "-G--",
]
env = GridWorldEnv(map = map, reward_dict = reward_dict, max_timestep = 100)

In [6]:
sarsa = SarsaAgent(env)
sarsa.train()
sarsa.save('sarsa_qtable.npy')
print(sarsa.qtable)

ep = 120, eposilon = 0.94, reached goals = 112, terminated = 0:   1%|          | 84/10000 [00:00<00:11, 835.24it/s]

SARSA TRAINING


ep = 6518, eposilon = 0.04, reached goals = 6486, terminated = 0:  64%|██████▍   | 6447/10000 [00:07<00:03, 1149.62it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

ep = 9999, eposilon = 0.01, reached goals = 9967, terminated = 0: 100%|██████████| 10000/10000 [00:11<00:00, 894.33it/s]


[[-2.84985739e+00 -5.77639100e-01  1.04966582e+00 -2.80294743e+00]
 [-2.07291462e+00 -1.18998546e+00  1.94907928e+00 -1.68196200e+00]
 [-2.03542232e+00 -7.77083409e-01 -6.93353559e-01 -2.12070509e+00]
 [-3.28477886e+00 -3.37473337e+00 -2.94021150e+00 -2.82921632e+00]
 [-1.51458368e+00  3.73362005e+00 -6.01328737e-01 -1.28590569e+00]
 [-1.44775825e+00  7.80834576e+00  3.35209409e+00 -1.76199547e+00]
 [-1.79715181e+00 -1.29711917e+00  2.05393307e+00  1.17109091e-01]
 [-5.41199361e-03 -1.92343463e+00 -1.10873752e+00 -1.29221049e+00]
 [-1.59255809e+00  8.06030082e-01  2.77440564e+00 -1.04467740e+00]
 [-2.85403491e-01 -1.55082543e-01  9.15435043e+00 -7.34617951e-01]
 [-2.14755039e+00 -1.12107435e+00  5.10618168e+00  2.59495517e+00]
 [-1.32932268e+00 -1.54807676e+00 -2.35309958e-01 -8.45572967e-01]
 [-1.28045186e+00  8.27071590e+00  2.02194126e-01  1.20528426e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.67611045e-01 -5.46868465e-01  1.86010978e+00  9.96807254e

In [13]:
agent = QLearningAgent(env)
agent.train()
agent.save()
# agent.load('./qtable.npy')
print(agent.qtable)

ep = 111, eposilon = 0.95, reached goals = 102, terminated = 0:   0%|          | 47/10000 [00:00<00:21, 468.36it/s]

TRAINING


ep = 5259, eposilon = 0.08, reached goals = 5218, terminated = 0:  52%|█████▏    | 5245/10000 [00:05<00:03, 1232.18it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

ep = 9999, eposilon = 0.01, reached goals = 9958, terminated = 0: 100%|██████████| 10000/10000 [00:10<00:00, 946.20it/s]


[[ 3.35589007e+00  1.07407134e+01  2.78065723e+00  3.32754592e+00]
 [ 4.50142953e+00  1.24799731e+01  6.63576151e+00  4.26374987e+00]
 [ 6.72721347e+00  1.42437004e+01  1.04932221e+01  3.71167943e+00]
 [ 2.64524169e+00  2.63388284e+00  7.52773889e+00  6.17444108e+00]
 [ 4.54215918e-01  6.46439407e+00 -1.58916899e+00 -6.49916401e-01]
 [ 2.07326223e+00  1.18016028e+01 -2.32921969e-01  1.91614070e-03]
 [ 5.00068090e+00  7.02898843e+00  2.48056413e+00  3.54923167e+00]
 [ 5.29607697e+00  5.15210317e+00  8.88406944e+00  7.01326972e+00]
 [-1.19968642e+00 -6.67758986e-01 -1.00067493e+00 -1.26361268e+00]
 [ 3.34866481e+00  1.96272971e-01 -2.35945481e-01 -1.40789255e+00]
 [ 1.64079195e+00  6.43330848e+00  2.31531247e+00 -4.68964597e-01]
 [ 3.94730521e+00  6.09586992e+00  9.99845511e+00  3.12735947e+00]
 [-1.44103976e+00 -6.18443658e-01 -1.02473808e+00 -1.08134930e+00]
 [-1.10865807e+00  2.14504673e+00 -7.26194165e-01 -1.02152993e+00]
 [-3.47597898e-01  6.95045867e+00  5.08172276e-01 -5.31373660e

In [7]:
# qtable_heatmap(agent.qtable)
for row in map:
    print(row)
agent_decision(sarsa.qtable)

A--B
--B-
R---
-G--


[['down', 'down', 'down', 'left'],
 ['right', 'right', 'down', 'up'],
 ['down', 'down', 'down', 'down'],
 ['right', 'up', 'left', 'left']]

In [7]:
env.reset()
print(env)

ENV MAP
['A', '-', '-', 'B']
['-', '-', '-', '-']
['B', 'R', '-', '-']
['-', '-', '-', 'G']
ENV STATE
[[1.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
ENV DESCRIPTION
reward dict = {'G': 10, 'B': 10, 'R': -1, 'S': -1, 'out_of_bound': -2, 'visited_state': -3, 'terminated': -1}
timestep = 0, max_timestep = 100,
obs space = 16
actions = 4
agent position = [0, 0]
goal position = [3, 3]
terminated = False



In [8]:
#Test the enviroment rewards and stuff
info = env.step(1)
print(env.state)
for row in env.map:
    print(row)
print(info)

[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
['A', '-', '-', 'B']
['-', '-', '-', '-']
['R', '-', '-', '-']
['-', '-', '-', 'G']
(15, 10, True, False, {})


In [9]:
env.render_simple(agent)

MAP
['A', '-', '-', 'B']
['-', '-', '-', '-']
['R', '-', '-', '-']
['-', '-', '-', 'G']
[[1.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 1(right) to state 1 done = False, terminated = False
[[0.  1.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 1(right) to state 2 done = False, terminated = False
[[0.  0.  1.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 1(right) to state 3 done = False, terminated = False
[[0.  0.  0.  1. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 2(down) to state 7 done = False, terminated = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 2(down) to state 11 done = False, terminated = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.  0.  0.5]]
took action = 2(down) to state 15 done = True, terminated = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.

In [10]:
env.render(agent)

/Users/jamesnguyen/Desktop/ml_projects/rl/src
exit


SystemExit: 1

/Users/jamesnguyen/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3534: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
