In [1]:
from src.env import GridWorldRenderer, GridWorldEnv
from src.agent import QLearningAgent
import numpy as np
import os

In [2]:
# map = [
#     ['A', 'R', '', 'S'],
#     ['', '', '', ''],
#     ['B', '', 'B', 'R'],
#     ['', '', '', 'G']
#     ]

# rows = 4 
# cols =4 

# def gen_obj():
#     choices = ['R', 'S', 'B', '-']
#     weights =  [0.05, 0.05, 0.05, 0.85]
#     return np.random.choice(choices, p = weights)

# map = [[gen_obj() for _ in range(rows)] for _ in range(cols)]
# map[0][0] = 'A'
# map[rows - 1][cols - 1] = 'G'

# map = [''.join(row) for row in map]

# for row in map:
#     print(row)

In [3]:
reward_dict = {
    'G': 10,
    'B': 0,
    'R': -1,
    'S': -2,
    'out-of-bound': -5,
    'terminated': -3,
}
map = [
    "A---",
    "----",
    "BR--",
    "---G",
]
env = GridWorldEnv(map = map, reward_dict = reward_dict, max_timestep = 100)

In [4]:
agent = QLearningAgent(env)
agent.train()
agent.save()
# agent.load('./qtable.npy')
print(agent.qtable)

ep = 45, eposilon = 0.98, reached goals = 40, terminated = 0:   0%|          | 27/10000 [00:00<00:42, 235.75it/s]

TRAINING


ep = 9999, eposilon = 0.01, reached goals = 9962, terminated = 0: 100%|██████████| 10000/10000 [00:17<00:00, 571.34it/s]


[[-1.72615612  6.39429121  1.84856592 -1.78906748]
 [-1.07267963  7.31047399  3.85133389  2.75249927]
 [-0.15759753  4.2891763   8.16486842  3.408369  ]
 [-1.33924326 -1.35079315  7.89717182  2.24591361]
 [ 0.95839751  4.15001187  0.07794229 -3.0146295 ]
 [ 1.89656403  7.34320754  0.37696919  0.92551939]
 [ 4.61696195  8.87862704  4.95590416  3.88738165]
 [ 4.77050274  2.31322071  9.45415533  5.69671275]
 [ 0.17979524 -0.20622284  0.46186048 -2.29599608]
 [ 0.76844126  3.94204356  0.93918471  0.04328451]
 [ 2.99901103  4.89385606  8.14994263  0.25250755]
 [ 5.98495805  2.8913561   9.98690775  4.52109837]
 [ 0.02982089  1.91063232 -2.11818611 -2.18900016]
 [-0.09875942  5.7695121  -1.72897735  0.20947166]
 [ 2.59113863  9.64159065  0.86218838  1.82617068]
 [ 0.          0.          0.          0.        ]]


In [5]:
#Test the enviroment rewards and stuff
info = env.step(2)
print(env.state)
for row in env.map:
    print(row)
print(info)

[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
['A', '-', '-', '-']
['-', '-', '-', '-']
['B', 'R', '-', '-']
['-', '-', '-', 'G']
(15, 10, True, False, {})


In [6]:
env.reset()
print(env.state)
env.render_simple(agent)

[[1.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
MAP
['A', '-', '-', '-']
['-', '-', '-', '-']
['B', 'R', '-', '-']
['-', '-', '-', 'G']
took action =  1  to state  1 done = False
[[0.  1.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action =  1  to state  2 done = False
[[0.  0.  1.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action =  2  to state  6 done = False
[[0.  0.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action =  1  to state  7 done = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action =  2  to state  11 done = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.  0.  0.5]]
took action =  2  to state  15 done = True
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action =  0  to state  11 done = True
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.  0.  

KeyboardInterrupt: 