In [4]:
from src.env import GridWorldRenderer, GridWorldEnv
from src.agent import QLearningAgent
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from src.utils import qtable_heatmap, agent_decision

In [6]:
# map = [
#     ['A', 'R', '', 'S'],
#     ['', '', '', ''],
#     ['B', '', 'B', 'R'],
#     ['', '', '', 'G']
#     ]

# rows = 4 
# cols =4 

# def gen_obj():
#     choices = ['R', 'S', 'B', '-']
#     weights =  [0.05, 0.05, 0.05, 0.85]
#     return np.random.choice(choices, p = weights)

# map = [[gen_obj() for _ in range(rows)] for _ in range(cols)]
# map[0][0] = 'A'
# map[rows - 1][cols - 1] = 'G'

# map = [''.join(row) for row in map]

# for row in map:
#     print(row)

In [5]:
reward_dict = {
    'G': 10,
    'B': 10,
    'R': -1,
    'S': -1,
    'out_of_bound': -2,
    'visited_state': -3,
    'terminated': -1,
}
map = [
    "A--B",
    "----",
    "R---",
    "---G",
]
env = GridWorldEnv(map = map, reward_dict = reward_dict, max_timestep = 100)

In [6]:
agent = QLearningAgent(env)
agent.train()
agent.save()
# agent.load('./qtable.npy')
print(agent.qtable)

ep = 128, eposilon = 0.94, reached goals = 113, terminated = 0:   1%|▏         | 128/10000 [00:00<00:15, 648.29it/s]

TRAINING


ep = 8412, eposilon = 0.02, reached goals = 8355, terminated = 0:  83%|████████▎ | 8319/10000 [00:09<00:01, 915.71it/s] IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

ep = 9999, eposilon = 0.01, reached goals = 9942, terminated = 0: 100%|██████████| 10000/10000 [00:11<00:00, 854.48it/s]


[[ 3.77282696 10.47033396  0.60192399  3.87184433]
 [ 5.03010672 12.28905592 -0.27561267  4.01335007]
 [ 6.41893152 14.07866422  1.8316088   3.53908589]
 [ 2.072393    2.14478668  7.58174311  5.70162999]
 [ 4.33376285 -1.33333085 -1.79081482 -1.62997462]
 [ 0.58483279 -0.22715357  1.63350124 -1.32275523]
 [ 2.66498507  1.83688272  5.1642776  -1.31556878]
 [ 1.72318391  3.33244983  8.87460742  1.26227739]
 [-1.62987212 -0.30677972 -1.19065717 -1.58614179]
 [-1.88753142  1.42684024  4.75797189 -1.82529865]
 [-0.55906856  4.08573457  8.03085299  0.03133273]
 [ 2.20761147  4.33648279  9.94459099  3.20938665]
 [-1.90985852  0.95559794 -1.39168338 -1.36700239]
 [-1.0434703   7.64686161  1.05476695 -1.12643336]
 [ 1.76895482  9.91360202  4.16977978  1.75738789]
 [ 0.          0.          0.          0.        ]]


In [23]:
print(type(np.zeros((2,2))))

<class 'numpy.ndarray'>


In [7]:
# qtable_heatmap(agent.qtable)
for row in map:
    print(row)
agent_decision(agent.qtable)

A--B
----
R---
---G


[['right', 'right', 'right', 'down'],
 ['up', 'down', 'down', 'down'],
 ['right', 'down', 'down', 'down'],
 ['right', 'right', 'right', 'up']]

In [7]:
env.reset()
print(env)

ENV MAP
['A', '-', '-', 'B']
['-', '-', '-', '-']
['B', 'R', '-', '-']
['-', '-', '-', 'G']
ENV STATE
[[1.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
ENV DESCRIPTION
reward dict = {'G': 10, 'B': 10, 'R': -1, 'S': -1, 'out_of_bound': -2, 'visited_state': -3, 'terminated': -1}
timestep = 0, max_timestep = 100,
obs space = 16
actions = 4
agent position = [0, 0]
goal position = [3, 3]
terminated = False



In [8]:
#Test the enviroment rewards and stuff
info = env.step(1)
print(env.state)
for row in env.map:
    print(row)
print(info)

[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
['A', '-', '-', 'B']
['-', '-', '-', '-']
['R', '-', '-', '-']
['-', '-', '-', 'G']
(15, 10, True, False, {})


In [9]:
env.render_simple(agent)

MAP
['A', '-', '-', 'B']
['-', '-', '-', '-']
['R', '-', '-', '-']
['-', '-', '-', 'G']
[[1.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 1(right) to state 1 done = False, terminated = False
[[0.  1.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 1(right) to state 2 done = False, terminated = False
[[0.  0.  1.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 1(right) to state 3 done = False, terminated = False
[[0.  0.  0.  1. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 2(down) to state 7 done = False, terminated = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 2(down) to state 11 done = False, terminated = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  1. ]
 [0.  0.  0.  0.5]]
took action = 2(down) to state 15 done = True, terminated = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.

In [10]:
env.render(agent)

/Users/jamesnguyen/Desktop/ml_projects/rl/src
exit


SystemExit: 1

/Users/jamesnguyen/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3534: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
