In [1]:
from src.env import GridWorldRenderer, GridWorldEnv
from src.agent import QLearningAgent, SarsaAgent
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from src.utils import qtable_heatmap, agent_decision

In [6]:
# map = [
#     ['A', 'R', '', 'S'],
#     ['', '', '', ''],
#     ['B', '', 'B', 'R'],
#     ['', '', '', 'G']
#     ]

# rows = 4 
# cols =4 

# def gen_obj():
#     choices = ['R', 'S', 'B', '-']
#     weights =  [0.05, 0.05, 0.05, 0.85]
#     return np.random.choice(choices, p = weights)

# map = [[gen_obj() for _ in range(rows)] for _ in range(cols)]
# map[0][0] = 'A'
# map[rows - 1][cols - 1] = 'G'

# map = [''.join(row) for row in map]

# for row in map:
#     print(row)

In [17]:
reward_dict = {
    'G': 2,
    'B': 1,
    'R': -1,
    'S': -1,
    'out_of_bound': -2,
    'visited_state': -3,
    'terminated': -1,
}
map = [
    "A--B",
    "--B-",
    "--R-",
    "-G--",
]
env = GridWorldEnv(map = map, reward_dict = reward_dict, max_timestep = 100)

In [19]:
sarsa = SarsaAgent(env)
sarsa.train()
sarsa.save('sarsa_qtable.npy')
print(sarsa.qtable)

ep = 147, eposilon = 0.93, reached goals = 143, terminated = 0:   1%|          | 76/10000 [00:00<00:13, 735.15it/s]

SARSA TRAINING


ep = 5166, eposilon = 0.08, reached goals = 5151, terminated = 0:  51%|█████     | 5060/10000 [00:05<00:04, 999.37it/s] IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

ep = 9999, eposilon = 0.01, reached goals = 9984, terminated = 0: 100%|██████████| 10000/10000 [00:10<00:00, 935.50it/s]


[[-3.80263866 -1.80746115 -1.7768429  -3.79497191]
 [-2.5798375  -1.3766983  -1.16091978 -2.12243121]
 [-1.66152014 -1.22158614 -1.21818818 -2.25473943]
 [-1.97566313 -1.97369212 -1.97234457 -1.97614144]
 [-2.23929575 -1.11278307 -0.9828525  -2.7540952 ]
 [-2.65567846 -0.676666    0.14273485 -1.97289196]
 [-1.58782896 -1.58060624 -1.57771316 -1.59012188]
 [-1.65626729 -1.68359584 -1.63651842 -1.6568831 ]
 [-3.19469494 -0.17804516  0.21645768 -2.03436399]
 [-2.06055764 -1.20790421  1.94440403 -1.07431086]
 [-1.43123032 -1.10871532 -0.32020397 -0.69732022]
 [-1.84701109 -1.48983406 -1.38179854 -1.38203157]
 [-2.36542982  1.96809276 -1.14281991 -1.0839391 ]
 [ 0.          0.          0.          0.        ]
 [-1.66029092 -1.35422144 -0.9598052   1.79298977]
 [-1.77716644 -1.27190984 -1.30614337 -0.71493277]]


In [16]:
# qtable_heatmap(agent.qtable)
for row in map:
    print(row)
agent_decision(sarsa.qtable)

A--B
--B-
--R-
-G--


[['down', 'down', 'down', 'right'],
 ['down', 'down', 'down', 'up'],
 ['down', 'down', 'down', 'down'],
 ['right', 'up', 'left', 'left']]

# Q learning

In [ ]:
agent = QLearningAgent(env)
agent.train()
agent.save()
# agent.load('./qtable.npy')
print(agent.qtable)

In [18]:
env.reset()
print(env)

ENV MAP
['A', '-', '-', 'B']
['-', '-', 'B', '-']
['-', '-', 'R', '-']
['-', 'G', '-', '-']
ENV STATE
[[1.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
ENV DESCRIPTION
reward dict = {'G': 2, 'B': 1, 'R': -1, 'S': -1, 'out_of_bound': -2, 'visited_state': -3, 'terminated': -1}
timestep = 0, max_timestep = 100,
obs space = 16
actions = 4
agent position = [0, 0]
goal position = [3, 3]
terminated = False



In [8]:
#Test the enviroment rewards and stuff
info = env.step(1)
print(env.state)
for row in env.map:
    print(row)
print(info)

[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
['A', '-', '-', 'B']
['-', '-', '-', '-']
['R', '-', '-', '-']
['-', '-', '-', 'G']
(15, 10, True, False, {})


In [9]:
env.render_simple(sarsa)

MAP
['A', '-', '-', 'B']
['-', '-', 'B', '-']
['R', '-', '-', '-']
['-', 'G', '-', '-']
[[1.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 2(down) to state 4 done = False, terminated = False
[[0.  0.  0.  0. ]
 [1.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 1(right) to state 5 done = False, terminated = False
[[0.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 1(right) to state 6 done = False, terminated = False
[[0.  0.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.5]]
took action = 2(down) to state 10 done = False, terminated = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  1.  0. ]
 [0.  0.  0.  0.5]]
took action = 2(down) to state 14 done = False, terminated = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  1.  0.5]]
took action = 3(left) to state 13 done = True, terminated = False
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.

In [10]:
env.render(agent)

/Users/jamesnguyen/Desktop/ml_projects/rl/src
exit


SystemExit: 1

/Users/jamesnguyen/anaconda3/envs/torch/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3534: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
