In [1]:
from src.env import GridWorldRenderer, GridWorldEnv, GET_RANDOM_MAP
from src.agent import QLearningAgent, SarsaAgent
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from src.utils import qtable_heatmap, agent_decision

In [2]:
# map = [
#     ['A', 'R', '', 'S'],
#     ['', '', '', ''],
#     ['B', '', 'B', 'R'],
#     ['', '', '', 'G']
#     ]

# rows = 4 
# cols =4 

# def gen_obj():
#     choices = ['R', 'S', 'B', '-']
#     weights =  [0.05, 0.05, 0.05, 0.85]
#     return np.random.choice(choices, p = weights)

# map = [[gen_obj() for _ in range(rows)] for _ in range(cols)]
# map[0][0] = 'A'
# map[rows - 1][cols - 1] = 'G'

# map = [''.join(row) for row in map]

# for row in map:
#     print(row)

In [3]:
reward_dict = {
    'G': 3,
    'B': 1,
    'R': -1,
    'S': -1,
    'out_of_bound': -1,
    'visited_state': -1,
    'terminated': -1,
}
map = [
    "A--B",
    "----",
    "B---",
    "---G",
]
map = GET_RANDOM_MAP(20,20)
#print map
for row in map:
    print(row)
env = GridWorldEnv(map = map, reward_dict = reward_dict, max_timestep = 100)

A---------S---------
-S--B-S-------------
--------------------
-BB---B-------S-----
-----S----R---R-R-B-
--------------------
----B-RB----R-------
----B-S--BBB----R---
----B------B-R--SR-R
--------B-------S---
----B-R-------------
--S-S------B--R-R---
--------------------
-R---RS-B----------R
-S------------------
---BB-----------B---
RR-B---------B-B----
-S-R----R--S----B---
----------R------SS-
-B-B-----R-----S--BG


# Q learning

In [4]:
agent = QLearningAgent(env)
agent.train()
agent.save()
# agent.load('./qtable.npy')
print(agent.qtable)

ep = 47, eposilon = 0.98, reached goals = 0, terminated = 0:   0%|          | 32/10000 [00:00<00:31, 319.75it/s]

QLEARNING TRAINING


ep = 9999, eposilon = 0.01, reached goals = 2291, terminated = 0: 100%|██████████| 10000/10000 [00:22<00:00, 449.61it/s]


[[-1.21450365 -0.56749061  0.02514333 -1.22077751]
 [-1.05043354 -0.52960973 -0.82786263 -0.51598876]
 [-0.84485525 -0.40387199 -0.40223104 -0.91237065]
 ...
 [-0.26181874  1.4841019  -0.0886721  -0.1736285 ]
 [-0.19878882  2.11838526  0.0436909  -0.0452697 ]
 [ 0.          0.          0.          0.        ]]


In [5]:
env.reset()
print(env)

ENV MAP
['A', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'S', '-', '-', '-', '-', '-', '-', '-', '-', '-']
['-', 'S', '-', '-', 'B', '-', 'S', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-']
['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-']
['-', 'B', 'B', '-', '-', '-', 'B', '-', '-', '-', '-', '-', '-', '-', 'S', '-', '-', '-', '-', '-']
['-', '-', '-', '-', '-', 'S', '-', '-', '-', '-', 'R', '-', '-', '-', 'R', '-', 'R', '-', 'B', '-']
['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-']
['-', '-', '-', '-', 'B', '-', 'R', 'B', '-', '-', '-', '-', 'R', '-', '-', '-', '-', '-', '-', '-']
['-', '-', '-', '-', 'B', '-', 'S', '-', '-', 'B', 'B', 'B', '-', '-', '-', '-', 'R', '-', '-', '-']
['-', '-', '-', '-', 'B', '-', '-', '-', '-', '-', '-', 'B', '-', 'R', '-', '-', 'S', 'R', '-', 'R']
['-', '-', '-', '-', '-', '-', '-', '-', 'B', '-', '-', '-', '-', '-', '-', '-', 'S

In [6]:
#Test the enviroment rewards and stuff
# info = env.step(2)
# print(env.state)
# for row in env.map:
#     print(row)
# print(info)

In [7]:
# env.render_simple(agent)

In [8]:
env.render(agent)

/Users/jamesnguyen/Desktop/ml_projects/rl/src
exit
Terminated


: 